### PR TITLE
Adding Matthew voice (American male)

### PR DESCRIPTION
**Pull request by Hugobox**
Hi! 
First thanks for the node! Here's a little PR to add the voice of Matthew.

### CODE REVIEW

**Comment by arunkumar9t2** [comment]
@Rawa Any possibility to get this merged? Thanks.

**Comment by Rawa** [comment]
Sorry been very busy with work. Yes ofcourse. Merged @arunkumar9t2

**Comment by arunkumar9t2** [comment]
No problem. Thanks a lot for your work!

**Comment by Hugobox** [comment]
@Rawa Could you bump version to NPM whenever you have time? Thanks!

**Comment by Rawa** [comment]
@Hugobox bumped.

**Pull request merged**
